// <auto-generated />
using System;
using APBDTask9.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APBDTask9.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260519181430_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APBDTask9.Models.ComponentManufacture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FoundationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ComponentManufactures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "INTL",
                            FoundationDate = new DateTime(1968, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Intel Corporation"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "AMD",
                            FoundationDate = new DateTime(1969, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Advanced Micro Devices"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "NVDA",
                            FoundationDate = new DateTime(1993, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Nvidia Corporation"
                        });
                });

            modelBuilder.Entity("APBDTask9.Models.ComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ComponentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "CPU",
                            Name = "Central Processing Unit"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "GPU",
                            Name = "Graphics Processing Unit"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "RAM",
                            Name = "Random Access Memory"
                        });
                });

            modelBuilder.Entity("APBDTask9.Models.Componets", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("ComponentManufactorId")
                        .HasColumnType("int");

                    b.Property<int>("ComponentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Desciption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.HasIndex("ComponentManufactorId");

                    b.HasIndex("ComponentTypeId");

                    b.ToTable("Componets");

                    b.HasData(
                        new
                        {
                            Code = "A",
                            ComponentManufactorId = 1,
                            ComponentTypeId = 1,
                            Desciption = "High end CPU",
                            Name = "Intel Core i9"
                        },
                        new
                        {
                            Code = "B",
                            ComponentManufactorId = 2,
                            ComponentTypeId = 2,
                            Desciption = "High end GPU",
                            Name = "AMD Radeon RX"
                        },
                        new
                        {
                            Code = "C",
                            ComponentManufactorId = 3,
                            ComponentTypeId = 2,
                            Desciption = "Top tier GPU",
                            Name = "Nvidia RTX 4090"
                        });
                });

            modelBuilder.Entity("APBDTask9.Models.PCComponets", b =>
                {
                    b.Property<int>("PCId")
                        .HasColumnType("int");

                    b.Property<string>("ComponetCode")
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("ComponetAmount")
                        .HasColumnType("int");

                    b.HasKey("PCId", "ComponetCode");

                    b.HasIndex("ComponetCode");

                    b.ToTable("PCComponets");

                    b.HasData(
                        new
                        {
                            PCId = 1,
                            ComponetCode = "A",
                            ComponetAmount = 1
                        },
                        new
                        {
                            PCId = 1,
                            ComponetCode = "B",
                            ComponetAmount = 2
                        },
                        new
                        {
                            PCId = 2,
                            ComponetCode = "C",
                            ComponetAmount = 1
                        });
                });

            modelBuilder.Entity("APBDTask9.Models.PCs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("PCs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gaming Beast X",
                            Stock = 5,
                            Warranty = 36,
                            Weight = 12.5f
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Office Mini Pro",
                            Stock = 12,
                            Warranty = 24,
                            Weight = 4.2f
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Workstation Pro",
                            Stock = 3,
                            Warranty = 48,
                            Weight = 8f
                        });
                });

            modelBuilder.Entity("APBDTask9.Models.Componets", b =>
                {
                    b.HasOne("APBDTask9.Models.ComponentManufacture", null)
                        .WithMany("Components")
                        .HasForeignKey("ComponentManufactorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APBDTask9.Models.ComponentType", null)
                        .WithMany("Components")
                        .HasForeignKey("ComponentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("APBDTask9.Models.PCComponets", b =>
                {
                    b.HasOne("APBDTask9.Models.Componets", null)
                        .WithMany("PcComponets")
                        .HasForeignKey("ComponetCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APBDTask9.Models.PCs", null)
                        .WithMany("PcComponets")
                        .HasForeignKey("PCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("APBDTask9.Models.ComponentManufacture", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("APBDTask9.Models.ComponentType", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("APBDTask9.Models.Componets", b =>
                {
                    b.Navigation("PcComponets");
                });

            modelBuilder.Entity("APBDTask9.Models.PCs", b =>
                {
                    b.Navigation("PcComponets");
                });
#pragma warning restore 612, 618
        }
    }
}
