// <auto-generated />
using System;
using APBDTask9.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APBDTask9.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APBDTask9.Models.ComponentManufacture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FoundationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ComponentManufactures");
                });

            modelBuilder.Entity("APBDTask9.Models.ComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ComponentTypes");
                });

            modelBuilder.Entity("APBDTask9.Models.Componets", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("ComponentManufactorId")
                        .HasColumnType("int");

                    b.Property<int>("ComponentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Desciption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.HasIndex("ComponentManufactorId");

                    b.HasIndex("ComponentTypeId");

                    b.ToTable("Componets");
                });

            modelBuilder.Entity("APBDTask9.Models.PCComponets", b =>
                {
                    b.Property<int>("PCId")
                        .HasColumnType("int");

                    b.Property<int>("ComponetAmount")
                        .HasColumnType("int");

                    b.Property<string>("ComponetCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("PCId");

                    b.HasIndex("ComponetCode");

                    b.ToTable("PCComponets");
                });

            modelBuilder.Entity("APBDTask9.Models.PCs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("PCs");
                });

            modelBuilder.Entity("APBDTask9.Models.Componets", b =>
                {
                    b.HasOne("APBDTask9.Models.ComponentManufacture", null)
                        .WithMany("Components")
                        .HasForeignKey("ComponentManufactorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APBDTask9.Models.ComponentType", null)
                        .WithMany("Components")
                        .HasForeignKey("ComponentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("APBDTask9.Models.PCComponets", b =>
                {
                    b.HasOne("APBDTask9.Models.Componets", null)
                        .WithMany("PcComponets")
                        .HasForeignKey("ComponetCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APBDTask9.Models.PCs", null)
                        .WithMany("PcComponets")
                        .HasForeignKey("PCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("APBDTask9.Models.ComponentManufacture", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("APBDTask9.Models.ComponentType", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("APBDTask9.Models.Componets", b =>
                {
                    b.Navigation("PcComponets");
                });

            modelBuilder.Entity("APBDTask9.Models.PCs", b =>
                {
                    b.Navigation("PcComponets");
                });
#pragma warning restore 612, 618
        }
    }
}
